version: '3'

services:
  iago:
    build:
      context: '.'
      dockerfile: Dockerfile-dataservants
    image: 'dataservants'
    container_name: 'iago'
    volumes:
      - ${DCDEVDIR}/config/:/home/lig/conf
      - ${DCDATADIR}/logs/lig:/home/lig/logs
    working_dir: /home/lig/Codes/DataServants/
    command: ["python", "Iago.py", "-l", "/home/lig/logs/iago.log", "-c", "/home/lig/conf/iago.conf", "-p", "/home/lig/conf/passwords.conf", "--debug"]
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always

  alfred:
    image: 'dataservants'
    container_name: 'alfred'
    volumes:
      - ${DCDEVDIR}/config/:/home/lig/conf
      - ${DCDATADIR}/logs/lig:/home/lig/logs
    working_dir: /home/lig/Codes/DataServants/
    command: ["python", "Alfred.py", "-l", "/home/lig/logs/alfred.log", "-c", "/home/lig/conf/alfred.conf", "-p", "/home/lig/conf/passwords.conf", "--extraPings", "/home/lig/conf/alfred_extraPings.conf", "--debug"]
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always

  abu:
    image: 'dataservants'
    container_name: 'abu'
    volumes:
      - ${DCDEVDIR}/config/:/home/lig/conf
      - ${DCDATADIR}/logs/lig:/home/lig/logs
        #    depends_on:
        #      - 'influxdb'
    working_dir: /home/lig/Codes/DataServants/
    command: ["python", "Abu.py", "-l", "/home/lig/logs/abu.log", "-c", "/home/lig/conf/abu.conf", "-p", "/home/lig/conf/passwords.conf", "--debug"]
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always

networks:
    default:
        driver: bridge
