version: '3'

services:
  apachephp:
    build:
      context: '.'
      dockerfile: 'webStackDockerfile'
      args:
        - php_version=${PHP_VERSION}
    container_name: 'allSkyCamStack'
    ports:
      - 8080:80
    networks:
      - default
    volumes:
      - ./test.php:/var/www/html/index.php
      - ./httpdOpts.conf:/etc/apache2/sites-enabled/000-default.conf
      - nfsmountCC:${NFSLDIR}

volumes:
  nfsmountCC:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSRIP}
      device: ":${NFSRDIR}"

networks:
  default:
    driver: bridge
