version: '3'

services:
  apachephp:
    build:
      context: '.'
      dockerfile: 'webStackDockerfile'
      args:
        - php_version=${PHP_VERSION}
    container_name: 'allSkyCamStack'
    ports:
      - 8080:80
    networks:
      - default
    volumes:
      - ./test.php:/var/www/html/index.php


networks:
  default:
    driver: bridge
