version: '3'

services:
  dct_asc_webcams:
   build:
      context: './dct_asc_scripts/'
      dockerfile: 'Dockerfile'
   container_name: 'dct_asc_cams'
   depends_on: 
      - "apachephp"
   volumes:
      - nfsmountCC:${NFSLDIR}
      - ./camimages:/home/lig/Codes/dct_asc/images
      - ./camimages/dct:/home/lig/Codes/dct_asc/images/dct
      - ./camimages/mesa:/home/lig/Codes/dct_asc/images/mesa
   working_dir: /home/lig/Codes/dct_asc/
   command: ["python", "camScheduler.py"]
   networks:
      - default

  apachephp:
    build:
      context: '.'
      dockerfile: 'webStackDockerfile'
      args:
        - php_version=${PHP_VERSION}
    container_name: 'allSkyCamStack'
    ports:
      - 8080:80
    networks:
      - default
    volumes:
#      - ./test.php:/var/www/html/index.php
      - ./allskysite/:/var/www/html/
      - ./httpdOpts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./camimages/:/var/www/html/webcams/:ro
      - nfsmountCC:${NFSLDIR}

volumes:
  nfsmountCC:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSRIP}
      device: ":${NFSRDIR}"

networks:
  default:
    driver: bridge
