version: '3'
services:
 omsa:
    container_name: omsa82
    image: jdelaros1/openmanage
    ports:
     - 1311:1311
    network_mode: "host"
    restart: always
    cap_add:
     - ALL
    privileged: true
    volumes:
     - "/lib/modules:/lib/modules:ro"
 jekyll:
    container_name: jekyll
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      #- 35729:35729
      #- 6000:3000
      -   80:4000
