version: '3'
services:
 omsa:
    container_name: omsa82
    image: jdelaros1/openmanage
    ports:
     - 1311:1311
    network_mode: "host"
    restart: always
    cap_add:
     - ALL
    privileged: true
    volumes:
     - "/lib/modules:/lib/modules:ro"
 nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
     - 80:80
    network_mode: "host"
    restart: always
    volumes:
     - $PWD/nginx_routing.conf:/etc/nginx/conf.d/default.conf
 jekyll:
    container_name: jekyll
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD/mainLandingPage/:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
     - 4000:4000
     #- 35729:35729
     #- 6000:3000
    network_mode: "host"
    restart: always
 portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/DockerData/portainer:/data
    network_mode: "host"
    restart: always

# gitlab:
#    image: gitlab/gitlab-ce:11.4.0-ce.0
#    container_name: gitlab
#    hostname: dctsleeperservice
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        gitlab_rails['gitlab_shell_ssh_port'] = 8822
#    ports:
#      - "443:443"
#      - "8880:80"
#      - "8822:22"
#    volumes:
#      - ./gitlab-logs:/var/log/gitlab
#      - ./gitlab-config:/etc/gitlab
#      - ./gitlab-data:/var/opt/gitlab
#    restart: always
