version: '3'

services:
  webcammcwebcamface:
    build:
      context: './Camelot/WebcamMcWebcamface'
      dockerfile: 'Dockerfile'
    container_name: 'webcammcwebcamface'
#    depends_on:
#      - "apachephp"
    volumes:
      - ${DCDATADIR}/logs/webcammcwebcamface:/home/lig/Codes/WebcamMcWebcamface/logs/
      - ${DCDATADIR}/webcammcwebcamface:/home/lig/Codes/WebcamMcWebcamface/images/
      - ${DCDEVDIR}/config/webcams.conf:/home/lig/Codes/WebcamMcWebcamface/webcams.conf
    working_dir: /home/lig/Codes/WebcamMcWebcamface
    command: ["python", "camLooper.py"]
    networks:
      - default
    restart: always

  goesmcgoesface:
    build:
      context: './Camelot/GOESMcGOESface/'
      dockerfile: 'Dockerfile'
    container_name: 'goesmcgoesface'
    depends_on:
#      - "apachephp"
      - "webcammcwebcamface"
    volumes:
      - ${DCDATADIR}/logs/goesmcgoesface/:/home/lig/Codes/GOESMcGOESface/logs/
      - ${DCDATADIR}/goesmcgoesface/:/home/lig/Codes/GOESMcGOESface/outputs/
      - ${DCDATADIR}/goesmcgoesface/cartopy:/home/lig/.local/share/cartopy/
      - ${DCDEVDIR}/config/awsCreds.conf:/home/lig/Codes/GOESMcGOESface/awsCreds.conf
    working_dir: /home/lig/Codes/GOESMcGOESface/
    command: ["python", "goes16aws_looper.py"]
    networks:
      - default
    restart: always

  apachephp:
    build:
      context: '.'
      dockerfile: 'webStackDockerfile'
      args:
        - php_version=${PHP_VERSION}
    container_name: 'NightWatchWeb'
    depends_on:
      - "goesmcgoesface"
      - "webcammcwebcamface"
    ports:
      - 8080:80
    networks:
      - default
    restart: always
    volumes:
      - ./httpdOpts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ${DCDATADIR}/goesmcgoesface/:/var/www/html/goes16
      - ${DCDATADIR}/webcammcwebcamface/:/var/www/html/dctwebcams

networks:
  default:
    driver: bridge
