version: '3'

services:
  webcammcwebcamface:
    build:
      context: './Camelot/WebcamMcWebcamface'
      dockerfile: 'Dockerfile'
    container_name: 'webcammcwebcamface'
    volumes:
      - ${DCDATADIR}/logs/webcammcwebcamface:/home/lig/Codes/WebcamMcWebcamface/logs/
      - ${DCDATADIR}/webcammcwebcamface:/home/lig/Codes/WebcamMcWebcamface/images/
      - ${DCDEVDIR}/config/webcams.conf:/home/lig/Codes/WebcamMcWebcamface/webcams.conf
    working_dir: /home/lig/Codes/WebcamMcWebcamface
    command: ["python", "camLooper.py"]
    networks:
      - default
    restart: always

  goesmcgoesface:
    build:
      context: './Camelot/GOESMcGOESface/'
      dockerfile: 'Dockerfile'
    container_name: 'goesmcgoesface'
    depends_on:
      - "webcammcwebcamface"
    volumes:
      - ${DCDATADIR}/logs/goesmcgoesface/:/home/lig/Codes/GOESMcGOESface/logs/
      - ${DCDATADIR}/goesmcgoesface/:/home/lig/Codes/GOESMcGOESface/outputs/
      - ${DCDATADIR}/goesmcgoesface/cartopy:/home/lig/.local/share/cartopy/
      - ${DCDEVDIR}/config/awsCreds.conf:/home/lig/Codes/GOESMcGOESface/awsCreds.conf
    working_dir: /home/lig/Codes/GOESMcGOESface/
    command: ["python", "goes16aws_looper.py"]
    networks:
      - default
    restart: always

  bokehmcbokehface:
    build:
      context: './Camelot/BokehMcBokehface/'
      dockerfile: 'Dockerfile'
    container_name: 'bokehmcbokehface'
    depends_on:
      - "webcammcwebcamface"
    volumes:
      - ${DCDATADIR}/logs/bokehmcbokehface/:/home/lig/Codes/BokehMcBokehface/logs/
      - ${DCDEVDIR}/config/dbqueries.conf:/home/lig/Codes/BokehMcBokehface/config/dbqueries.conf
      - ${DCDEVDIR}/config/modules.conf:/home/lig/Codes/BokehMcBokehface/config/modules.conf
    working_dir: /home/lig/Codes/BokehMcBokehface/
    environment:
      - BOKEH_LOG_LEVEL=debug
      - BOKEH_PY_LOG_LEVEL=debug
      - BOKEH_PRETTY=true
    command: ["python", "serve.py"]
    ports:
      - 5000:5000
    networks:
      - default
    restart: always

  djangostack:
    build:
      context: '.'
      dockerfile: 'webStackDockerfile'
    container_name: 'djangostack'
    depends_on:
      - "goesmcgoesface"
      - "webcammcwebcamface"
      - "bokehmcbokehface"
    ports:
      - 9876:8113
    networks:
      - default
    restart: always
    volumes:
      - ${DCDATADIR}/goesmcgoesface/:/home/djdock/goes16
      - ${DCDATADIR}/webcammcwebcamface/:/home/djdock/webcams

networks:
  default:
    driver: bridge
